[package]
name = "basis-universal"
version = "0.0.1"
authors = ["Philip Degarmo <aclysma@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/aclysma/basis-universal-rs"
homepage = "https://github.com/aclysma/basis-universal-rs"
description = "Bindings for the basis-universal Supercompressed GPU Texture Codec by Binomial"
keywords = ["game", "graphics", "basis", "basis-universal", "universal", "texture", "compression", "mipmaps", "dds", "ktx", "image", "transcoding", "gpu", "binomial", "supercompressed", "supercompression"]
categories = ["game-development", "game-engines", "graphics", "multimedia", "rendering::engine", "api-bindings", "compression", "encoding"]

[dependencies]
basis-universal-sys = { version = "00.0.1", path = "../basis-universal-sys"}
lazy_static = "1.4.0"

[dev-dependencies]
image = "0.23.13"